language: java
sudo: false # faster builds
jdk:
  - openjdk6
  - oraclejdk7
  - oraclejdk8
script: "mvn --show-version --errors --batch-mode clean verify"
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - roberto.trunfio@gmail.com